
package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FrequencyUnitSoap", targetNamespace = "http://www.webserviceX.NET/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FrequencyUnitSoap {


    /**
     * 
     * @param fromFrequencyUnit
     * @param toFrequencyUnit
     * @param frequencyValue
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ChangeFrequencyUnit", action = "http://www.webserviceX.NET/ChangeFrequencyUnit")
    @WebResult(name = "ChangeFrequencyUnitResult", targetNamespace = "http://www.webserviceX.NET/")
    @RequestWrapper(localName = "ChangeFrequencyUnit", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeFrequencyUnit")
    @ResponseWrapper(localName = "ChangeFrequencyUnitResponse", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeFrequencyUnitResponse")
    public double changeFrequencyUnit(
        @WebParam(name = "FrequencyValue", targetNamespace = "http://www.webserviceX.NET/")
        double frequencyValue,
        @WebParam(name = "fromFrequencyUnit", targetNamespace = "http://www.webserviceX.NET/")
        Frequencys fromFrequencyUnit,
        @WebParam(name = "toFrequencyUnit", targetNamespace = "http://www.webserviceX.NET/")
        Frequencys toFrequencyUnit);

}
